### ISSUE TITLE
Return service_time_idwhen getting records

### ISSUE THREAD

**Issue by tcavaletto** [lifechurch/churchmetrics-api#12]
We have multiple campuses that share the same service times (e.g. two campuses both with a service at 9:00am Sunday) and are having difficulties grabbing all records for a particular campus's service time using the service_date_time and campus.id fields. Could you also return the service_time_id on each record when someone hits GET /records.json? / having the service_time_id as an optional parameter?

**Comment by okcscott** [comment]
Good question @tcavaletto. Let me give you a little background 1st. The way Church Metrics was originally designed was that records and service times are independent of each other. This was done so that records wouldn't change if a service time was update. 

Say you had 100 people at your 10:00 am service last Sunday. This weekend your 10:00 is moving to 10:30. Well, you still had 100 people at your 10 last week, even though the service time has moved. So, to accomplish this, many developers ago, the decision was made to keep those 2 things separate. Because of that, there is no `service_time_id` on a record, unfortunately.

2 things:

1. This is something we are wanting to change and improve. So, in the future (don't have a date for you) service times & records will be related through a foreign key like `service_time_id`.
2. To get around this today, what most churches do is they loop over their campuses, and pass the `campus_id` to the records call. This will bring back records only for that campus.

Sorry I didn't have a better solution for you Taylor! And once service times & records know about each other, we'll update you.

**Comment by tcavaletto** [comment]
@okcscott Thanks for the help, the campus_id method'll work great.
